// Code generated by MockGen. DO NOT EDIT.
// Source: matcher.go
//
// Generated by this command:
//
//	mockgen -source matcher.go -destination matcher_mock.go -package matching . Matcher
//

// Package matching is a generated GoMock package.
package matching

import (
	context "context"
	reflect "reflect"

	models "github.com/formancehq/reconciliation/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockMatcher) Match(ctx context.Context, transaction *models.Transaction) (*MatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ctx, transaction)
	ret0, _ := ret[0].(*MatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Match indicates an expected call of Match.
func (mr *MockMatcherMockRecorder) Match(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockMatcher)(nil).Match), ctx, transaction)
}
