// Code generated by MockGen. DO NOT EDIT.
// Source: anomalies.go
//
// Generated by this command:
//
//	mockgen -source anomalies.go -destination anomalies_mock.go -package storage . AnomalyRepository
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/v3/bun/bunpaginate"
	models "github.com/formancehq/reconciliation/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAnomalyRepository is a mock of AnomalyRepository interface.
type MockAnomalyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnomalyRepositoryMockRecorder
	isgomock struct{}
}

// MockAnomalyRepositoryMockRecorder is the mock recorder for MockAnomalyRepository.
type MockAnomalyRepositoryMockRecorder struct {
	mock *MockAnomalyRepository
}

// NewMockAnomalyRepository creates a new mock instance.
func NewMockAnomalyRepository(ctrl *gomock.Controller) *MockAnomalyRepository {
	mock := &MockAnomalyRepository{ctrl: ctrl}
	mock.recorder = &MockAnomalyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnomalyRepository) EXPECT() *MockAnomalyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnomalyRepository) Create(ctx context.Context, anomaly *models.Anomaly) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, anomaly)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnomalyRepositoryMockRecorder) Create(ctx, anomaly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnomalyRepository)(nil).Create), ctx, anomaly)
}

// FindOpenByTransactionIDs mocks base method.
func (m *MockAnomalyRepository) FindOpenByTransactionIDs(ctx context.Context, transactionIDs []uuid.UUID) ([]models.Anomaly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpenByTransactionIDs", ctx, transactionIDs)
	ret0, _ := ret[0].([]models.Anomaly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOpenByTransactionIDs indicates an expected call of FindOpenByTransactionIDs.
func (mr *MockAnomalyRepositoryMockRecorder) FindOpenByTransactionIDs(ctx, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpenByTransactionIDs", reflect.TypeOf((*MockAnomalyRepository)(nil).FindOpenByTransactionIDs), ctx, transactionIDs)
}

// GetByID mocks base method.
func (m *MockAnomalyRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Anomaly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Anomaly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAnomalyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAnomalyRepository)(nil).GetByID), ctx, id)
}

// ListByPolicy mocks base method.
func (m *MockAnomalyRepository) ListByPolicy(ctx context.Context, q GetAnomaliesQuery) (*bunpaginate.Cursor[models.Anomaly], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPolicy", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Anomaly])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPolicy indicates an expected call of ListByPolicy.
func (mr *MockAnomalyRepositoryMockRecorder) ListByPolicy(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPolicy", reflect.TypeOf((*MockAnomalyRepository)(nil).ListByPolicy), ctx, q)
}

// Resolve mocks base method.
func (m *MockAnomalyRepository) Resolve(ctx context.Context, id uuid.UUID, resolvedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, id, resolvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockAnomalyRepositoryMockRecorder) Resolve(ctx, id, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockAnomalyRepository)(nil).Resolve), ctx, id, resolvedBy)
}
