// Code generated by MockGen. DO NOT EDIT.
// Source: matches.go
//
// Generated by this command:
//
//	mockgen -source matches.go -destination matches_mock.go -package storage . MatchRepository
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/v3/bun/bunpaginate"
	models "github.com/formancehq/reconciliation/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRepository is a mock of MatchRepository interface.
type MockMatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRepositoryMockRecorder is the mock recorder for MockMatchRepository.
type MockMatchRepositoryMockRecorder struct {
	mock *MockMatchRepository
}

// NewMockMatchRepository creates a new mock instance.
func NewMockMatchRepository(ctrl *gomock.Controller) *MockMatchRepository {
	mock := &MockMatchRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRepository) EXPECT() *MockMatchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMatchRepository) Create(ctx context.Context, match *models.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMatchRepositoryMockRecorder) Create(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMatchRepository)(nil).Create), ctx, match)
}

// GetByID mocks base method.
func (m *MockMatchRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMatchRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMatchRepository)(nil).GetByID), ctx, id)
}

// ListByPolicy mocks base method.
func (m *MockMatchRepository) ListByPolicy(ctx context.Context, q GetMatchesQuery) (*bunpaginate.Cursor[models.Match], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPolicy", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Match])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPolicy indicates an expected call of ListByPolicy.
func (mr *MockMatchRepositoryMockRecorder) ListByPolicy(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPolicy", reflect.TypeOf((*MockMatchRepository)(nil).ListByPolicy), ctx, q)
}

// UpdateDecision mocks base method.
func (m *MockMatchRepository) UpdateDecision(ctx context.Context, id uuid.UUID, decision models.Decision) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDecision", ctx, id, decision)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDecision indicates an expected call of UpdateDecision.
func (mr *MockMatchRepositoryMockRecorder) UpdateDecision(ctx, id, decision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDecision", reflect.TypeOf((*MockMatchRepository)(nil).UpdateDecision), ctx, id, decision)
}
