// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_store.go
//
// Generated by this command:
//
//	mockgen -source transaction_store.go -destination transaction_store_mock.go -package storage . TransactionStore
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	models "github.com/formancehq/reconciliation/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionStore is a mock of TransactionStore interface.
type MockTransactionStore struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionStoreMockRecorder
	isgomock struct{}
}

// MockTransactionStoreMockRecorder is the mock recorder for MockTransactionStore.
type MockTransactionStoreMockRecorder struct {
	mock *MockTransactionStore
}

// NewMockTransactionStore creates a new mock instance.
func NewMockTransactionStore(ctrl *gomock.Controller) *MockTransactionStore {
	mock := &MockTransactionStore{ctrl: ctrl}
	mock.recorder = &MockTransactionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionStore) EXPECT() *MockTransactionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionStore) Create(ctx context.Context, tx *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionStoreMockRecorder) Create(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionStore)(nil).Create), ctx, tx)
}

// CreateBatch mocks base method.
func (m *MockTransactionStore) CreateBatch(ctx context.Context, txs []*models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockTransactionStoreMockRecorder) CreateBatch(ctx, txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockTransactionStore)(nil).CreateBatch), ctx, txs)
}

// ExistsByExternalIDs mocks base method.
func (m *MockTransactionStore) ExistsByExternalIDs(ctx context.Context, side models.TransactionSide, externalIDs []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByExternalIDs", ctx, side, externalIDs)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByExternalIDs indicates an expected call of ExistsByExternalIDs.
func (mr *MockTransactionStoreMockRecorder) ExistsByExternalIDs(ctx, side, externalIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByExternalIDs", reflect.TypeOf((*MockTransactionStore)(nil).ExistsByExternalIDs), ctx, side, externalIDs)
}

// GetByExternalID mocks base method.
func (m *MockTransactionStore) GetByExternalID(ctx context.Context, side models.TransactionSide, externalID string) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, side, externalID)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockTransactionStoreMockRecorder) GetByExternalID(ctx, side, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockTransactionStore)(nil).GetByExternalID), ctx, side, externalID)
}

// GetByID mocks base method.
func (m *MockTransactionStore) GetByID(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionStore)(nil).GetByID), ctx, id)
}

// GetByProvider mocks base method.
func (m *MockTransactionStore) GetByProvider(ctx context.Context, provider string, side models.TransactionSide) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProvider", ctx, provider, side)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProvider indicates an expected call of GetByProvider.
func (mr *MockTransactionStoreMockRecorder) GetByProvider(ctx, provider, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProvider", reflect.TypeOf((*MockTransactionStore)(nil).GetByProvider), ctx, provider, side)
}

// Refresh mocks base method.
func (m *MockTransactionStore) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTransactionStoreMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTransactionStore)(nil).Refresh), ctx)
}

// SearchByField mocks base method.
func (m *MockTransactionStore) SearchByField(ctx context.Context, side models.TransactionSide, field, value string) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByField", ctx, side, field, value)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByField indicates an expected call of SearchByField.
func (mr *MockTransactionStoreMockRecorder) SearchByField(ctx, side, field, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByField", reflect.TypeOf((*MockTransactionStore)(nil).SearchByField), ctx, side, field, value)
}
