// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source backend.go -destination backend_generated.go -package backend . Service
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/v3/bun/bunpaginate"
	service "github.com/formancehq/reconciliation/internal/api/service"
	models "github.com/formancehq/reconciliation/internal/models"
	storage "github.com/formancehq/reconciliation/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreatePolicy mocks base method.
func (m *MockService) CreatePolicy(ctx context.Context, req *service.CreatePolicyRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", ctx, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockServiceMockRecorder) CreatePolicy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockService)(nil).CreatePolicy), ctx, req)
}

// CreateBackfill mocks base method.
func (m *MockService) CreateBackfill(ctx context.Context, req *service.CreateBackfillRequest) (*models.Backfill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackfill", ctx, req)
	ret0, _ := ret[0].(*models.Backfill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackfill indicates an expected call of CreateBackfill.
func (mr *MockServiceMockRecorder) CreateBackfill(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackfill", reflect.TypeOf((*MockService)(nil).CreateBackfill), ctx, req)
}

// GetBackfill mocks base method.
func (m *MockService) GetBackfill(ctx context.Context, id string) (*models.Backfill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackfill", ctx, id)
	ret0, _ := ret[0].(*models.Backfill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackfill indicates an expected call of GetBackfill.
func (mr *MockServiceMockRecorder) GetBackfill(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackfill", reflect.TypeOf((*MockService)(nil).GetBackfill), ctx, id)
}

// CreatePolicyV2Balance mocks base method.
func (m *MockService) CreatePolicyV2Balance(ctx context.Context, req *service.CreatePolicyV2BalanceRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicyV2Balance", ctx, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicyV2Balance indicates an expected call of CreatePolicyV2Balance.
func (mr *MockServiceMockRecorder) CreatePolicyV2Balance(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicyV2Balance", reflect.TypeOf((*MockService)(nil).CreatePolicyV2Balance), ctx, req)
}

// CreatePolicyV2Transaction mocks base method.
func (m *MockService) CreatePolicyV2Transaction(ctx context.Context, req *service.CreatePolicyV2TransactionRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicyV2Transaction", ctx, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicyV2Transaction indicates an expected call of CreatePolicyV2Transaction.
func (mr *MockServiceMockRecorder) CreatePolicyV2Transaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicyV2Transaction", reflect.TypeOf((*MockService)(nil).CreatePolicyV2Transaction), ctx, req)
}

// DeletePolicy mocks base method.
func (m *MockService) DeletePolicy(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockServiceMockRecorder) DeletePolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockService)(nil).DeletePolicy), ctx, id)
}

// DeleteTransactionsByProvider mocks base method.
func (m *MockService) DeleteTransactionsByProvider(ctx context.Context, provider string, side models.TransactionSide) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransactionsByProvider", ctx, provider, side)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransactionsByProvider indicates an expected call of DeleteTransactionsByProvider.
func (mr *MockServiceMockRecorder) DeleteTransactionsByProvider(ctx, provider, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionsByProvider", reflect.TypeOf((*MockService)(nil).DeleteTransactionsByProvider), ctx, provider, side)
}

// ForceMatch mocks base method.
func (m *MockService) ForceMatch(ctx context.Context, policyID string, req *service.ForceMatchRequest, resolvedBy string) (*models.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceMatch", ctx, policyID, req, resolvedBy)
	ret0, _ := ret[0].(*models.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForceMatch indicates an expected call of ForceMatch.
func (mr *MockServiceMockRecorder) ForceMatch(ctx, policyID, req, resolvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceMatch", reflect.TypeOf((*MockService)(nil).ForceMatch), ctx, policyID, req, resolvedBy)
}

// GetAnomalyByID mocks base method.
func (m *MockService) GetAnomalyByID(ctx context.Context, anomalyID string) (*service.AnomalyDetailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnomalyByID", ctx, anomalyID)
	ret0, _ := ret[0].(*service.AnomalyDetailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnomalyByID indicates an expected call of GetAnomalyByID.
func (mr *MockServiceMockRecorder) GetAnomalyByID(ctx, anomalyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnomalyByID", reflect.TypeOf((*MockService)(nil).GetAnomalyByID), ctx, anomalyID)
}

// GetLatestPolicyReport mocks base method.
func (m *MockService) GetLatestPolicyReport(ctx context.Context, policyID string) (*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPolicyReport", ctx, policyID)
	ret0, _ := ret[0].(*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPolicyReport indicates an expected call of GetLatestPolicyReport.
func (mr *MockServiceMockRecorder) GetLatestPolicyReport(ctx, policyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPolicyReport", reflect.TypeOf((*MockService)(nil).GetLatestPolicyReport), ctx, policyID)
}

// GetPolicy mocks base method.
func (m *MockService) GetPolicy(ctx context.Context, id string) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, id)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockServiceMockRecorder) GetPolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockService)(nil).GetPolicy), ctx, id)
}

// GetReconciliation mocks base method.
func (m *MockService) GetReconciliation(ctx context.Context, id string) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReconciliation", ctx, id)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReconciliation indicates an expected call of GetReconciliation.
func (mr *MockServiceMockRecorder) GetReconciliation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReconciliation", reflect.TypeOf((*MockService)(nil).GetReconciliation), ctx, id)
}

// GetTransactionsByProvider mocks base method.
func (m *MockService) GetTransactionsByProvider(ctx context.Context, provider string, side models.TransactionSide) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByProvider", ctx, provider, side)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByProvider indicates an expected call of GetTransactionsByProvider.
func (mr *MockServiceMockRecorder) GetTransactionsByProvider(ctx, provider, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByProvider", reflect.TypeOf((*MockService)(nil).GetTransactionsByProvider), ctx, provider, side)
}

// ListPolicies mocks base method.
func (m *MockService) ListPolicies(ctx context.Context, q storage.GetPoliciesQuery) (*bunpaginate.Cursor[models.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockServiceMockRecorder) ListPolicies(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockService)(nil).ListPolicies), ctx, q)
}

// ListAnomalies mocks base method.
func (m *MockService) ListAnomalies(ctx context.Context, q storage.GetAnomaliesQuery) (*bunpaginate.Cursor[models.Anomaly], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnomalies", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Anomaly])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnomalies indicates an expected call of ListAnomalies.
func (mr *MockServiceMockRecorder) ListAnomalies(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnomalies", reflect.TypeOf((*MockService)(nil).ListAnomalies), ctx, q)
}

// ListPolicyAnomalies mocks base method.
func (m *MockService) ListPolicyAnomalies(ctx context.Context, policyID string, q storage.GetAnomaliesQuery) (*bunpaginate.Cursor[models.Anomaly], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicyAnomalies", ctx, policyID, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Anomaly])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicyAnomalies indicates an expected call of ListPolicyAnomalies.
func (mr *MockServiceMockRecorder) ListPolicyAnomalies(ctx, policyID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicyAnomalies", reflect.TypeOf((*MockService)(nil).ListPolicyAnomalies), ctx, policyID, q)
}

// ListReconciliations mocks base method.
func (m *MockService) ListReconciliations(ctx context.Context, q storage.GetReconciliationsQuery) (*bunpaginate.Cursor[models.Reconciliation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReconciliations", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Reconciliation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReconciliations indicates an expected call of ListReconciliations.
func (mr *MockServiceMockRecorder) ListReconciliations(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReconciliations", reflect.TypeOf((*MockService)(nil).ListReconciliations), ctx, q)
}

// MatchTransactions mocks base method.
func (m *MockService) MatchTransactions(ctx context.Context, policyID string, transactionIDs []string) ([]service.MatchResultV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchTransactions", ctx, policyID, transactionIDs)
	ret0, _ := ret[0].([]service.MatchResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchTransactions indicates an expected call of MatchTransactions.
func (mr *MockServiceMockRecorder) MatchTransactions(ctx, policyID, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchTransactions", reflect.TypeOf((*MockService)(nil).MatchTransactions), ctx, policyID, transactionIDs)
}

// Reconciliation mocks base method.
func (m *MockService) Reconciliation(ctx context.Context, policyID string, req *service.ReconciliationRequest) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconciliation", ctx, policyID, req)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconciliation indicates an expected call of Reconciliation.
func (mr *MockServiceMockRecorder) Reconciliation(ctx, policyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconciliation", reflect.TypeOf((*MockService)(nil).Reconciliation), ctx, policyID, req)
}

// TriggerPolicyMatching mocks base method.
func (m *MockService) TriggerPolicyMatching(ctx context.Context, policyID string) ([]service.MatchResultV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerPolicyMatching", ctx, policyID)
	ret0, _ := ret[0].([]service.MatchResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerPolicyMatching indicates an expected call of TriggerPolicyMatching.
func (mr *MockServiceMockRecorder) TriggerPolicyMatching(ctx, policyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerPolicyMatching", reflect.TypeOf((*MockService)(nil).TriggerPolicyMatching), ctx, policyID)
}

// UpdatePolicy mocks base method.
func (m *MockService) UpdatePolicy(ctx context.Context, id string, req *service.UpdatePolicyRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", ctx, id, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockServiceMockRecorder) UpdatePolicy(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockService)(nil).UpdatePolicy), ctx, id, req)
}

// UpdatePolicyV2 mocks base method.
func (m *MockService) UpdatePolicyV2(ctx context.Context, id string, req *service.UpdatePolicyV2Request) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicyV2", ctx, id, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicyV2 indicates an expected call of UpdatePolicyV2.
func (mr *MockServiceMockRecorder) UpdatePolicyV2(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicyV2", reflect.TypeOf((*MockService)(nil).UpdatePolicyV2), ctx, id, req)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// GetService mocks base method.
func (m *MockBackend) GetService() Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(Service)
	return ret0
}

// GetService indicates an expected call of GetService.
func (mr *MockBackendMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockBackend)(nil).GetService))
}
